#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Kadono Kodai
# SPDX-License-Identifier: BSD-3-Clause
def plus(*numbers):
    ans = 0
    for i in numbers:
        ans += i
    return ans

def main():
  numbers = []
  while True:
    num = input("足したい数値を入力: ")
    try:
      numbers.append(int(num))
    except ValueError:
      print("整数値を入力してください。")
      continue
    if num == "":
      break

    result = plus(*numbers)

    print(f"{numbers} の合計は {result} です。")

if __name__ == "__main__":
  main()
