#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Kadono Kodai
# SPDX-License-Identifier: BSD-3-Clause
import sys

def main():
    numbers = []
    for line in sys.stdin:
        num = line.strip()
        if not num:
            break
        try:
            numbers.append(float(num))
        except ValueError:
            print("ValluError")

    result = sum(numbers)
    print(result)

if __name__ == "__main__":
    main()